version: '2'
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:3.13
    ports:
      - "4444:4444"
  couchdb:
    container_name: couchdb
    image: ${COUCHDB_IMAGE}
    environment:
      COUCHDB_USER: tester
      COUCHDB_PASSWORD: testerpass
    ports:
      - "5984:5984"
