version: '2'
services:
  selenium:
    extends:
      file: './dc.selenium.yml'
      service: selenium
    container_name: selenium
    image: selenium/standalone-chrome-debug:3.13
    ports:
      - "4444:4444"
      - "5900:5900"
  couchdb:
    extends:
      file: './dc.selenium.yml'
      service: couchdb
